name: "GitHub Issue Check"
description: "Check to see if a GitHub Issue is linked to a PR and fail if not."
inputs:
  github_token:
    description: "A GitHub Token that can be used to authenticate to the GitHub API"
  valid_issue_state:
    description: |
      An issue state to consider as valid
      (e.g. to only count open issues)
runs:
  using: "node16"
  main: "dist/index.js"
