site_name: "github-action-require-issue"
docs_dir: "docs"
#site_url: https://example.com/
repo_url: "https://github.com/SpotOnInc/github-action-require-issue"
nav:
  - Home: index.md
  - Usage: usage.md
dev_addr: 127.0.0.1:8383

extra_css:
  - stylesheets/spoton.css

theme:
  name: material
  font:
    text: Poppins
  icon:
    logo: octicons/issue-tracked-by-16
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    # Back to top button
    - navigation.top
    # Use instant loading for internal links
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    - content.code.annotate
    # Enable copy-to-clipboard button
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings
  - minify:
      minify_html: true
