name: pull-request

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    push:
      branches:
        - 'main'

jobs:
  verify-not-dependabot:
    name: Check for Dependabot
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.dependacheck.outputs.status }}
    steps:
      - name: Who goes there?
        id: dependacheck
        run: |
          [[ "${{github.actor}}" == "dependabot[bot]" ]] && status="skip" || status="check"
          echo $status
          echo "status=$status" >> $GITHUB_OUTPUT

  checks:
    name: Perform required PR checks
    runs-on: ubuntu-latest
    needs: verify-not-dependabot
    if: needs.verify-not-dependabot.outputs.status == 'check'
    strategy:
      fail-fast: false
    steps:
      - name: Require linked issue on pull request
        uses: spotoninc/github-action-require-issue@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          valid_issue_state: open

      - uses: actions/checkout@v3

      # install deps
      - run: npm install

      - name: Run pre-commit on pull-request too to enforce rules
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --color=always --show-diff-on-failure

      # run tests and coverage analysis
      - run: npm run coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
