on:
  release:
    types: [released]

jobs:
  create-tag:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create generic version tag based on release tag
        run: |
          echo "tag_name=$(echo ${{ github.ref_name }} | sed -E 's/^(v[0-9]+)\.[0-9]+\.[0-9]+$/\1/')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Create generic tag
        uses: rickstaa/action-create-tag@v1
        with:
          commit_sha: ${{ github.sha }}
          tag: ${{ env.tag_name }}
          force_push_tag: true

